name: Infrastructure Destroy

on:
  repository_dispatch:
    types: [event-destroy-infra]

env:
  ACTION_TYPE: "DESTROY_INFRA"

jobs:
  # ----------------------------------------------------
  #             RESOURCE DESTROY
  # ----------------------------------------------------
  resource_destroy:
    name: Destroy Infrastructure (Terraform)
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_TF_STATE_FILE_BUCKET }}" \
            -backend-config="key=${{ secrets.AWS_TF_STATE_FILE_PATH }}" \
            -backend-config="region=${{ secrets.AWS_REGION_NAME }}" \
            -backend-config="encrypt=true"

      - name: Prepare Destroy Context
        run: |
          echo '{"ui_manifest": []}' > terraform.tfvars.json

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Reset Remote Manifest State
        if: success()
        run: |
          echo "[]" > empty.json
          aws s3 cp empty.json "s3://${{ secrets.AWS_TF_STATE_FILE_BUCKET }}/${{ secrets.AWS_TF_STATE_MANIFEST_FILE_PATH }}"

  # ----------------------------------------------------
  #             CLEAR SECRETS MANAGER
  # ----------------------------------------------------
  # ----------------------------------------------------
  #             CLEAR SECRETS MANAGER
  # ----------------------------------------------------
  clear_secrets:
    name: Clear Secrets Manager
    needs: resource_destroy
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Clear AWS Secret
        run: python .github/workflows/secretsManager.py
        env:
          AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
          SECRET_FILE_NAME: ${{ secrets.SECRETS_FILE_NAME }}
          ACTION_TYPE: ${{ env.ACTION_TYPE }}